"""ZP_DATABASE

Revision ID: 16a56e1018be
Revises: 2cf47bb8e896
Create Date: 2023-06-16 15:58:36.162438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a56e1018be'
down_revision = '2cf47bb8e896'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('Zarplata', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('data_p', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'data_p')
    op.drop_column('User', 'Zarplata')
    # ### end Alembic commands ###
